export const seasonPalettes = {
    lightSpring: {
        description: "Light Spring is warm and fresh. Its colours are light, delicate, and softly vibrant",

        bestColorsDescription: "light, warm and clear colours.",
        bestColors: [
            "#b294c6", 
            "#badeb8", 
            "#f3b785", 
            "#b5d7f2", 
            "#fef2c2", 
            "#f4aba5", 
            "#fbf4e0", 
            "#d7c5ad", 
            "#a6835b", 
        ],
        worstColorsDescription: "dark, heavy, and muted colours.",
        worstColors: [
            "#592e42", 
            "#0c393e", 
            "#560e0f", 
            "#3a4750", 
            "#050608", 
            "#554d4a", 
            "#483524", 
            "#864421",
        ]

    },
trueSpring: {
    description: "True Spring is clear and warm. Its palette feels lively, bright, and energetic.",
    bestColorsDescription: "bright, warm, and vibrant colours.",
     bestColors: [
            "#367b80", 
            "#42875b", 
            "#8ab051", 
            "#50b19c", 
            "#fae374", 
            "#eb675a", 
            "#fbfae8", 
            "#ca944d", 
            "#9a623e", 
        ],
    worstColorsDescription: "Flesh-toned neutrals, and muted pastels.",
    worstColors: [
            "#7a4b1f", 
            "#634e1f", 
            "#f8bf56", 
            "#f47f20", 
            "#b7583a", 
            "#6d7870", 
            "#9bafb6", 
            "#bba6af",
        ]
},

brightSpring: {
    description: "Bright Spring is bold and warm. Its colours are vivid, bright, and high contrast.",
    bestColorsDescription: "clear, bold, and high-contrast colours.",
    bestColors: [
            "#7f52a1", 
            "#c7d563", 
            "#f8cd53", 
            "#4a73b7", 
            "#459258", 
            "#ea3625", 
            "#d7c6b0", 
            "#828282", 
            "#5d3c27", 
        ],
    worstColorsDescription: "soft, dull, and muted colours.",
    worstColors: [
            "#edacca", 
            "#af7fb1", 
            "#5e6d8c", 
            "#949599", 
            "#ffffff", 
            "#3f464e", 
            "#23314b", 
            "#863256",
        ]
},

lightSummer: {
    description: "Light Summer is cool and airy. Its colours are soft, light, and pastel-like.",
    bestColorsDescription: "light, cool, and soft colours.",
    bestColors: [
            "#4570b8", 
            "#5abfa8", 
            "#da448b", 
            "#a899c9", 
            "#d6edde", 
            "#f2b7d4", 
            "#faf7c6", 
            "#708bc6", 
            "#a2a6a9", 
        ],
    worstColorsDescription: "dark, harsh, and overpowering colours.",
    worstColors: [
            "#2a1911", 
            "#0d301a", 
            "#281026", 
            "#43141e", 
            "#8e3f1e", 
            "#8f742d", 
            "#ce402c", 
            "#ed8a23",
        ]
},

trueSummer: {
    description: "True Summer is cool and muted. Its palette feels elegant, calm, and balanced.",
    bestColorsDescription: "cool, muted, and balanced colours.",
    bestColors: [
            "#4396ba", 
            "#44958c", 
            "#c34b71", 
            "#8abedf", 
            "#6ec0a4", 
            "#d172a4", 
            "#adbade", 
            "#fefbda", 
            "#375f98", 
        ],
    worstColorsDescription: "earthy warm tones with yellow undertones.",
    worstColors: [
            "#f8a78c", 
            "#f48448", 
            "#a65625", 
            "#90401f", 
            "#d9a329", 
            "#f9bf13", 
            "#f1592a", 
            "#cb3f28",
        ]
},

softSummer: {
    description: "Soft Summer is muted and cool. Its colours are smoky, gentle, and understated.",
    bestColorsDescription: "soft, cool, and muted colours.",
    bestColors: [
            "#546a90", 
            "#648484", 
            "#965f6f", 
            "#867a8c", 
            "#547668", 
            "#dca8b5", 
            "#faefc5", 
            "#d2c9c8", 
            "#979b9e", 
        ],
    worstColorsDescription: "electric, neon, rich warm hues.",
    worstColors: [
            "#050608", 
            "#ed1b24", 
            "#ee3497", 
            "#fef200", 
            "#6ebe45", 
            "#f16739", 
            "#c1a02f", 
            "#3a2313",
        ]
},

softAutumn: {
    description: "Soft Autumn is warm and muted. Its colours are earthy, soft, and relaxed.",
    bestColorsDescription: "muted, warm, and earthy colours.",
    bestColors: [
            "#985540", 
            "#d4a39e", 
            "#edc288", 
            "#636176", 
            "#7c99ad", 
            "#98c7c0", 
            "#666e55", 
            "#716f50", 
            "#969774", 
        ],
    worstColorsDescription: "harsh, bright colours.",
    worstColors: [
            "#000000", 
            "#ee1a88", 
            "#f1592a", 
            "#f5ed30", 
            "#8cc63e", 
            "#d6de27", 
            "#2e3192", 
            "#57585a",
        ]
    
},

trueAutumn: {
    description: "True Autumn is rich and warm. Its palette feels deep, earthy, and grounded.",
    bestColorsDescription: "rich, warm, and earthy colours.",
    bestColors: [
            "#b44a27", 
            "#e58733", 
            "#faae53", 
            "#744523", 
            "#c93b26", 
            "#cf5528", 
            "#4f5730", 
            "#4b7e41", 
            "#627334", 
        ],
    worstColorsDescription: "light dusty tints, overpowering hues.",
    worstColors: [
            "#f9d7e7", 
            "#b7dbf1", 
            "#9caed6", 
            "#dbc2df", 
            "#d2e8c4", 
            "#a8a9ad", 
            "#050608", 
            "#ef328e",
        ]
},

deepAutumn: {
    description: "Deep Autumn is dark and warm. Its colours are rich, dramatic, and intense.",
    bestColorsDescription: "deep, warm, and rich colours.",
    bestColors: [
            "#48140f", 
            "#913a21", 
            "#c87e4b", 
            "#1e3a28", 
            "#4a7152", 
            "#616128", 
            "#14313e", 
            "#275d6f", 
            "#2f6fa2", 
        ],
    worstColorsDescription: "soft pastels, cool dusty tones.",
    worstColors: [
            "#ffffff", 
            "#bba5af", 
            "#9db0b6", 
            "#596677", 
            "#9f6c7f", 
            "#f38aab", 
            "#444c56", 
            "#808281",
        ]
},

deepWinter: {
    description: "Deep Winter is cool and bold. Its palette combines depth with strong contrast.",
    bestColorsDescription: "deep, cool, and bold colours.",
    bestColors: [
            "#411e4a", 
            "#7d152b", 
            "#ac2e4f", 
            "#102c26", 
            "#317162", 
            "#b64d80", 
            "#1c4456", 
            "#418fc2", 
            "#286170", 
        ],
    worstColorsDescription: "rich warm tones, golden beige, nudes.",
    worstColors: [
            "#8c421f", 
            "#bd5927", 
            "#b66828", 
            "#ee9922", 
            "#e2c565", 
            "#dec98a", 
            "#f8e49d", 
            "#e4b776",
        ]
},

trueWinter: {
    description: "True Winter is cool and crisp. Its colours are sharp, saturated, and striking.",
    bestColorsDescription: "cool, crisp, and saturated colours.",
    bestColors: [
            "#30398f", 
            "#703898", 
            "#cb2c39", 
            "#419369", 
            "#c34a77", 
            "#f2c5dd", 
            "#3758a8", 
            "#878f93", 
            "#1d2b50", 
        ],
    worstColorsDescription: "warm golden and soft tones.",
    worstColors: [
            "#a45326", 
            "#a27645", 
            "#d9b428", 
            "#a9ae86", 
            "#a39e36", 
            "#f9b29e", 
            "#f3a189", 
            "#a95b59",
        ]
},

brightWinter: {
    description: "Bright Winter is vivid and cool. Its palette is intense, bright, and high contrast.",
    bestColorsDescription: "bright, cool, and high-contrast colours.",
    bestColors: [
            "#2e3391", 
            "#4ba073", 
            "#d8403f", 
            "#73c3ec", 
            "#eae859", 
            "#e43892", 
            "#e2f2fd", 
            "#646466", 
            "#000000", 
        ],
    worstColorsDescription: "rusty warm shades, dusty pastels.",
    worstColors: [
            "#51220e", 
            "#57431e", 
            "#a25625", 
            "#a03724", 
            "#f6bd56", 
            "#f6dec6", 
            "#86b6c2", 
            "#c0b6bf",
        ]
},
}
